name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@2.3.36
        with:
          project_name: ${{ github.repository }}
          cx_tenant: ama-partners
          base_uri: https://ind.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          branch: ${{ github.head_ref || github.ref_name }}
          scan_params: "--project-groups Inflow --project-tags dhruv-demo"
